import Link from "next/link";
import { AdminSidebar } from "@/src/components/admin-sidebar";
import { listAssessments } from "@/src/lib/assessment-repository";
import { requireAdmin } from "@/src/lib/admin-auth";

export default async function AdminDashboard() {
  await requireAdmin();
  const assessments = await listAssessments();
  const live = assessments.filter((a) => a.status === "LIVE");
  const completions = assessments.reduce((sum, assessment) => sum + assessment.completions, 0);
  return <div className="admin-shell"><AdminSidebar active="Overview" /><main className="admin-main"><div className="admin-top"><div><div className="eyebrow">Private workspace</div><h1>Good morning.</h1><p>Here is how your scorecards are performing.</p></div><div className="admin-actions"><Link className="button button-ghost" href="/">View public site ↗</Link><Link className="button button-primary" href="/admin/assessments/new">+ New assessment</Link></div></div><div className="stat-grid"><div className="stat-card"><p>Active assessments</p><strong>{live.length}</strong></div><div className="stat-card"><p>Total completions</p><strong>{completions}</strong></div><div className="stat-card"><p>Published products</p><strong>{live.length}</strong></div><div className="stat-card"><p>Contacts captured</p><strong>—</strong></div></div><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><h2>Your scorecards</h2><Link href="/admin/assessments">View all →</Link></div>{assessments.map((assessment) => <Link className="assessment-row" href={`/admin/assessments/${assessment.id}`} key={assessment.id}><div className="row-main"><div className="row-avatar">✦</div><div><strong>{assessment.name}</strong><span>{assessment.questionCount || "No"} questions · Updated {assessment.updatedAt}</span></div></div><span className={`tag ${assessment.status === "DRAFT" ? "draft" : ""}`}>{assessment.status}</span></Link>)}</section><section className="panel"><div className="panel-heading"><h2>Next steps</h2></div><div className="activity-row"><div className="activity-dot" /><div><p><strong>Create or refine a check-in</strong></p><span>Build questions, scoring and result content in one place.</span></div></div><div className="activity-row"><div className="activity-dot" /><div><p><strong>Test before publishing</strong></p><span>Complete the public link and confirm the report delivery.</span></div></div></section></div></main></div>;
}
