"use client";

import Link from "next/link";
import { useState } from "react";
import { AdminSidebar } from "@/src/components/admin-sidebar";

export function NewAssessmentForm() {
  const [name, setName] = useState("Your new assessment");
  const [saved, setSaved] = useState(false);
  return <div className="admin-shell"><AdminSidebar active="Assessments" /><main className="admin-main"><div className="page-title"><div><div className="eyebrow">Assessment studio</div><h1>Create an assessment</h1><p>Start with the basics. You can add questions, scoring and result content next.</p></div><Link className="button button-ghost" href="/admin/assessments">← Back to assessments</Link></div><div className="form-layout"><section className="form-card"><h2>Assessment basics</h2><p>This is the information people see before they begin. Keep it clear, warm and specific.</p><div className="field"><label htmlFor="name">Assessment name</label><input id="name" value={name} onChange={(event) => { setName(event.target.value); setSaved(false); }} /></div><div className="field"><label htmlFor="slug">Public URL</label><input id="slug" defaultValue="your-assessment" /></div><div className="field"><label htmlFor="tagline">Short tagline</label><input id="tagline" placeholder="A clearer view of what is really going on." /></div><div className="field"><label htmlFor="description">Introduction</label><textarea id="description" placeholder="Tell people what this check-in will help them understand..." /></div><div style={{ display: "flex", justifyContent: "flex-end", gap: 11, marginTop: 24 }}><button className="button button-ghost" type="button">Save as draft</button><button className="button button-primary" type="button" onClick={() => setSaved(true)}>{saved ? "Saved ✓" : "Continue to questions →"}</button></div></section><aside className="form-card"><div className="eyebrow">Live preview</div><div className="preview-box" style={{ marginTop: 17 }}><div className="eyebrow">Absolute Mind Check-in</div><h3>{name}</h3><p>A warm, focused introduction will appear here before someone begins their check-in.</p><div className="preview-line"><span>5 min check-in</span><span>0 questions yet</span></div></div><div style={{ borderTop: "1px solid var(--line)", marginTop: 24, paddingTop: 20 }}><div className="eyebrow">Next up</div><p className="muted" style={{ fontSize: 12, lineHeight: 1.6, marginBottom: 0 }}>Once the basics are saved, add sections and questions, then configure result bands and your call to action.</p></div></aside></div></main></div>;
}
